//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForcedLogin.Strings {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForcedLogin.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
    
        /// <summary>
            ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
            /// </summary>
            public static string SettingsPageAboutText {
                get {
                    return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to About this application.
            /// </summary>
            public static string SettingsPageAboutTitle {
                get {
                    return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Choose Theme.
            /// </summary>
            public static string SettingsPageChooseThemeText {
                get {
                    return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Personalization.
            /// </summary>
            public static string SettingsPagePersonalizationTitle {
                get {
                    return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Privacy Statement.
            /// </summary>
            public static string SettingsPagePrivacyStatementText {
                get {
                    return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Dark.
            /// </summary>
            public static string SettingsPageRadioButtonDarkTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Light.
            /// </summary>
            public static string SettingsPageRadioButtonLightTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to StatusUnauthorized.
        /// </summary>
        public static string StatusUnauthorized {
            get {
                return ResourceManager.GetString("StatusUnauthorized", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to StatusNoNetworkAvailable.
        /// </summary>
        public static string StatusNoNetworkAvailable {
            get {
                return ResourceManager.GetString("StatusNoNetworkAvailable", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to StatusLoginFails.
        /// </summary>
        public static string StatusLoginFails {
            get {
                return ResourceManager.GetString("StatusLoginFails", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to LogInPageTitle.
        /// </summary>
        public static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to LogInButton.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageUserTitle.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageLogOutButtonText.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
    }
}
